spring:
    application:
        name: SmartMatch
    datasource:
        url: jdbc:postgresql://localhost:5432/smartmatch_db
        username: postgres
        password: 20033691ecrin
    liquibase:
        change-log: classpath:db/changelog/db.changelog-master.yaml
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    data:
        redis:
            host: ${SPRING_DATA_REDIS_HOST:localhost}
            port: ${SPRING_DATA_REDIS_PORT:6379}

jwt:
    secret: ${JWT_SECRET:dGhpcy1pcy1hLXZlcnktc2VjdXJlLWFuZC1sb25nLXNlY3JldC1rZXktZm9yLWp3dC1hdXRoZW50aWNhdGlvbg==}
    access-token-expiration: 900000
    refresh-token-expiration: 604800000

gemini:
    api:
        key: ${GEMINI_API_KEY}
        url: "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent"